// noinspection JSUnusedGlobalSymbols

function createMeta( name, cat, desc, type, dv ) {
    return {
        name,
        category: cat,
        description: desc,
        defaultValue: dv,
        type
    }
}

export const themeVariableMetaList = [
createMeta('--rz-sz-std',            "standard sizes",   "The standard size for theming, set by the roots default, --rzd-sz. Used extensively to derive other sizes.", "size", 'var(--rzd-sz)'),
createMeta('--rz-sz-tiny',           "standard sizes",   "Much smaller size, .7 times --rz-sz-std.", "size", 'calc( 0.7 * var(--rz-sz-std) )'),
createMeta('--rz-sz-small',          "standard sizes",   "Smaller size, .85 times --rz-sz-std. ", "size", 'calc( 0.85 * var(--rz-sz-std) )'),
createMeta('--rz-sz-big',            "standard sizes",   "Larger size, 1.2 times --rz-sz-std. ", "size", 'calc( 1.2 * var(--rz-sz-std) )'),
createMeta('--rz-sz-huge',           "standard sizes",   "Much larger size, 2 times --rz-sz-std.", "size", 'calc( 2.0 * var(--rz-sz-std) )'),
createMeta('--rz-scale-dn-3',        "standard sizes",   "Variable to use in order to scale a value down by 30%", "size", '.7'),
createMeta('--rz-scale-dn-2',        "standard sizes",   "Variable to use in order to scale a value down by 20%", "size", '.8'),
createMeta('--rz-scale-dn-1',        "standard sizes",   "Variable to use in order to scale a value down by 10%", "size", '.9'),
createMeta('--rz-scale',             "standard sizes",   "Variable to be scaled against. Based on --rz-sz-std.", "size", 'var( --rz-sz-std )'),
createMeta('--rz-scale-up-1',        "standard sizes",   "Variable to use in order to scale a value by 10%", "size", '1.1'),
createMeta('--rz-scale-up-2',        "standard sizes",   "Variable to use in order to scale a value by 20%", "size", '1.2'),
createMeta('--rz-scale-up-3',        "standard sizes",   "Variable to use in order to scale a value by 30%", "size", '1.3'),
createMeta('--rz-black',             "standard colors",   "Standard black.", "color", 'black'),
createMeta('--rz-gray-0',            "standard colors",   "A black gray. gray-0 is the darkest gray.", "color", 'black'),
createMeta('--rz-gray-1',            "standard colors",   "A very dark gray. Not quite black.", "color", '#181818'),
createMeta('--rz-gray-2',            "standard colors",   "A dark gray.", "color", '#303030'),
createMeta('--rz-gray-3',            "standard colors",   "A slightly dark gray.", "color", '#505050'),
createMeta('--rz-gray-4',            "standard colors",   "The inherit gray as defined by the browser.", "color", 'grey'),
createMeta('--rz-gray-5',            "standard colors",   "A slightly lighter gray.", "color", '#a0a0a0'),
createMeta('--rz-gray',              "standard colors",   "rz's default gray. depends on --rz-gray-5 and is slightly lighter than the browsers default gray.", "color", 'var(--rz-gray-5)'),
createMeta('--rz-gray-6',            "standard colors",   "A lighter gray.", "color", '#bebebe'),
createMeta('--rz-gray-7',            "standard colors",   "A very light gray.", "color", '#d3d3d3'),
createMeta('--rz-gray-8',            "standard colors",   "An extremely light gray.", "color", '#e8e8e8'),
createMeta('--rz-gray-9',            "standard colors",   "An extraordinarily light gray.", "color", '#f8f8f8'),
createMeta('--rz-gray-X',            "standard colors",   "Infinitely lighter gray, aka white.", "color", 'white'),
createMeta('--rz-white',             "standard colors",   "Standard white.", "color", 'white'),
createMeta('--rz-bg-paper-0',        "standard colors",   "An off-white page background color.", "color", 'whitesmoke'),
createMeta('--rz-bg-paper-1',        "standard colors",   "An off-white page background color.", "color", '#EAE5E5FF'),
createMeta('--rz-bg-paper-2',        "standard colors",   "An off-white page background color.", "color", '#d0cece'),
createMeta('--rz-bg-selected',       "standard colors",   "A background color for something selected", "color", 'gold'),
createMeta('--rz-bg-hover',          "standard colors",   "A backgorund color that appears when hovering.", "color", 'cornsilk'),
createMeta('--rz-bg-stop',           "standard colors",   "description of this var", "color", 'rgba(234, 14, 25, 0.18)'),
createMeta('--rz-bg-caution',        "standard colors",   "description of this var", "color", 'rgba(178, 117, 66, 0.47)'),
createMeta('--rz-bg-go',             "standard colors",   "description of this var", "color", 'rgba(34, 128, 52, 0.33)'),
createMeta('--rz-bg-meta',           "standard colors",   "description of this var", "color", 'var(--rz-bg-paper-1)'),
createMeta('--rz-bg-important',      "standard colors",   "description of this var", "color", '#e3d8c3'),
createMeta('--rz-fg-text',           "standard colors",   "The standard text color. Derived from the root variable, --rzd-fg", "color", 'var(--rzd-fg)'),
createMeta('--rz-fg-dimmed',         "standard colors",   "description of this var", "color", 'var(--rz-gray-4)'),
createMeta('--rz-fg-faint',          "standard colors",   "description of this var", "color", 'var(--rz-gray-6)'),
createMeta('--rz-fg-title-1',        "standard colors",   "description of this var", "color", 'var(--rz-fg-text)'),
createMeta('--rz-fg-title-2',        "standard colors",   "description of this var", "color", 'var(--rz-fg-text)'),
createMeta('--rz-fg-selected',       "standard colors",   "Text color when selected.", "color", 'brown'),
createMeta('--rz-fg-go',             "standard colors",   "description of this var", "color", '#103410FF'),
createMeta('--rz-fg-good',           "standard colors",   "description of this var", "color", 'darkgreen'),
createMeta('--rz-fg-caution',        "standard colors",   "description of this var", "color", 'orange'),
createMeta('--rz-fg-danger',         "standard colors",   "description of this var", "color", 'red'),
createMeta('--rz-fg-error',          "standard colors",   "description of this var", "color", 'red'),
createMeta('--rz-fg-stop',           "standard colors",   "description of this var", "color", 'red'),
createMeta('--rz-fg-instruct',       "standard colors",   "description of this var", "color", 'saddlebrown'),
createMeta('--rz-fg-focus',          "standard colors",   "description of this var", "color", '#00008b'),
createMeta('--rz-fg-link',           "standard colors",   "Text color of a link.", "color", '#00000d'),
createMeta('--rz-fg-dirty',          "standard colors",   "description of this var", "color", 'red'),
createMeta('--rz-sb-w',              "standard sizes",   "description of this var", "size", '17px'),
createMeta('--rz-text-font',         "standard sizes",   "Sets the text font. Has two fallbacks incase browser doesn't support default.", "color", '"Helvetica-Neue", "Helvetica", "sans-serif"'),
createMeta('--rz-text-sz',           "standard sizes",   "Sets the default text font size.", "size", 'var( --rz-scale )'),
createMeta('--rz-hd-sz',             "standard sizes",   "Rz's default heading size, which is based on the current --rz-sz-big.", "size", 'var( --rz-sz-big )'),
createMeta('--rz-h1-sz',             "standard sizes",   "Rz's heading size for h1s.", "size", 'inherit'),
createMeta('--rz-h2-sz',             "standard sizes",   "Rz's heading size for h2s.", "size", 'inherit'),
createMeta('--rz-h3-sz',             "standard sizes",   "Rz's heading size for h3s.", "size", 'inherit'),
createMeta('--rz-h4-sz',             "standard sizes",   "Rz's heading size for h4s.", "size", 'inherit'),
createMeta('--rz-h5-sz',             "standard sizes",   "Rz's heading size for h5s.", "size", 'inherit'),
createMeta('--rz-h6-sz',             "standard sizes",   "Rz's heading size for h6s.", "size", 'inherit'),
createMeta('--rz-btn-pad',           "buttons", "A button padding variable to apply to any side", "size", '0.25em'),
createMeta('--rz-btn-bg',            "buttons", "The button background color, that is set to inherit from parent.", "color", 'inherit'),
createMeta('--rz-btn-bg_h',          "buttons", "description of this var", "color", 'inherit'),
createMeta('--rz-btn-bg_p',          "buttons", "description of this var", "color", '#79AFD7FF'),
createMeta('--rz-btn-bg_ph',         "buttons", "description of this var", "color", '#79AFD7AA'),
createMeta('--rz-btn-bg_p2',         "buttons", "description of this var", "color", '#6f6dd1'),
createMeta('--rz-btn-bg_i',          "buttons", "description of this var", "color", 'transparent'),
createMeta('--rz-btn-bg_ih',         "buttons", "description of this var", "color", 'transparent'),
createMeta('--rz-btn-fg',            "buttons", "Text color for a button", "color", 'var( --rz-gray-4 )'),
createMeta('--rz-btn-fg_d',          "buttons", "description of this var", "color", 'var( --rz-gray-6 )'),
createMeta('--rz-btn-fg_h',          "buttons", "description of this var", "color", 'var( --rz-gray-1 )'),
createMeta('--rz-btn-fg_f',          "buttons", "description of this var", "color", 'var( --rz-btn-fg_h )'),
createMeta('--rz-btn-fg_s',          "buttons", "description of this var", "color", 'var( --rz-btn-fg_h )'),
createMeta('--rz-btn-fg_p',          "buttons", "description of this var", "color", 'var( --rz-gray-X )'),
createMeta('--rz-btn-fg_ph',         "buttons", "description of this var", "color", 'var( --rz-gray-8 )'),
createMeta('--rz-btn-fg_i',          "buttons", "description of this var", "color", 'var( --rz-gray-5 )'),
createMeta('--rz-btn-fg_ih',         "buttons", "description of this var", "color", 'var( --rz-gray-7 )'),
createMeta('--rz-btn-sh',            "buttons", "description of this var", "color", 'none'),
createMeta('--rz-btn-br',            "buttons", "description of this var", "size", '6px'),
createMeta('--rz-btn-bw',            "buttons", "Defines button border width.", "size", '1px'),
createMeta('--rz-btn-bc',            "buttons", "Defines button border color.", "color", 'var( --rz-gray-6 )'),
createMeta('--rz-btn-bc_h',          "buttons", "Defines button border color when hovered over.", "color", 'var( --rz-gray-3 )'),
createMeta('--rz-btn-bc_f',          "buttons", "description of this var", "color", 'darkblue'),
createMeta('--rz-btn-bc_p',          "buttons", "description of this var", "color", 'var( --rz-btn-bg_p )'),
createMeta('--rz-btn-bc_i',          "buttons", "description of this var", "color", 'transparent'),
createMeta('--rz-btn-bc_ih',         "buttons", "description of this var", "color", 'var( --rz-btn-fg_ih )'),
createMeta('--rz-btn-text',          "buttons", "description of this var", "color", 'none'),
createMeta('--rz-btn-icon-fg',       "buttons", "Defines button icon foreground color.", "color", 'var( --rz-fg )'),
createMeta('--rz-btn-icon-bg',       "buttons", "Defines button icon background color.", "color", 'var( --rz-bg )'),
createMeta('--rz-btn-shadow',        "buttons", "Defines button border shadow. Default is none.", "other", '0 3px 6px 0 rgba(0,0,0,0.2)'),
createMeta('--rz-nav-bg',            "navs and links",   "A navigation background color.", "color", 'var(--rz-bg-paper-0)'),
createMeta('--rz-nav-fg',            "navs and links",   "A navigation text(foreground) color.", "color", 'var(--rz-fg-link)'),
createMeta('--rz-nav-bc',            "navs and links",   "A navigation border color.", "color", 'transparent'),
createMeta('--rz-nav-bg_d',          "navs and links",   "description of this var", "color", 'var(--rz-bg)'),
createMeta('--rz-nav-fg_d',          "navs and links",   "description of this var", "color", 'var(--rz-gray)'),
createMeta('--rz-nav-bc_d',          "navs and links",   "description of this var", "color", 'transparent'),
createMeta('--rz-nav-bg_h',          "navs and links",   "description of this var", "color", 'var(--rz-bg)'),
createMeta('--rz-nav-fg_h',          "navs and links",   "description of this var", "color", 'var(--rz-fg-link)'),
createMeta('--rz-nav-bc_h',          "navs and links",   "description of this var", "color", 'var(--rz-bc)'),
createMeta('--rz-nav-bg_s',          "navs and links",   "description of this var", "color", 'var(--rz-bg)'),
createMeta('--rz-nav-fg_s',          "navs and links",   "description of this var", "color", 'var(--rz-fg-link)'),
createMeta('--rz-nav-bc_s',          "navs and links",   "description of this var", "color", 'var(--rz-bc)'),
createMeta('--rz-nav-bg_f',          "navs and links",   "description of this var", "color", 'var(--rz-bg)'),
createMeta('--rz-nav-fg_f',          "navs and links",   "description of this var", "color", 'var(--rz-fg-link)'),
createMeta('--rz-nav-bc_f',          "navs and links",   "description of this var", "color", 'var(--rz-bc)'),
createMeta('--rz-nav-bg_v',          "navs and links",   "description of this var", "color", 'var(--rz-bg)'),
createMeta('--rz-nav-fg_v',          "navs and links",   "description of this var", "color", 'var(--rz-fg-link)'),
createMeta('--rz-nav-bc_v',          "navs and links",   "description of this var", "color", 'var(--rz-bc)'),
createMeta('--rz-nav-sz',            "navs and links",   "A navigations text size.", "size", '0.9rem'),
createMeta('--rz-nav-link-text',     "navs and links",   "A navigation link text size.", "color", 'uppercase'),
createMeta('--rz-menu-item-pad',     "navs and links",   "Defines padding for top/bottom and left/right for menus.", "other", '0.25rem 0.5rem'),
createMeta('--rz-link-pad',          "navs and links",   "Defines the padding around a link.", "other", '0.35em 0.35em '),
createMeta('--rz-link-sz',           "navs and links",   "A links text size.", "size", 'var(--rz-sz)'),
createMeta('--rz-link-bg',           "navs and links",   "A links background color.", "color", 'transparent'),
createMeta('--rz-link-fg',           "navs and links",   "A links text color.", "color", 'var(--rz-fg-link)'),
createMeta('--rz-link-bg_v',         "navs and links",   "description of this var", "color", 'transparent'),
createMeta('--rz-link-fg_v',         "navs and links",   "description of this var", "color", 'var(--rz-fg-link)'),
createMeta('--rz-link-bc',           "navs and links",   "A links border color.", "color", 'transparent'),
createMeta('--rz-link-text',         "navs and links",   "description of this var", "color", 'none'),
createMeta('--rz-page-pad',          "pages",   "Defines the padding on page. Default is 0.", "size", '0'),
createMeta('--rz-page-bc',           "pages",   "Sets the page border color. ", "color", 'none'),
createMeta('--rz-page-br',           "pages",   "description of this var", "color", 'none'),
createMeta('--rz-page-bg',           "pages",   "Defines the page background color.", "color", 'var(--rz-bg-paper-0)'),
createMeta('--rz-page-fg',           "pages",   "Defines the page foreground color.", "color", 'var(--rz-fg-text)'),
createMeta('--rz-page-fg_d',         "pages",   "description of this var", "color", 'var(--rz-gray-6)'),
createMeta('--rz-page-fg_s',         "pages",   "description of this var", "color", 'var(--rz-fg-selected)'),
createMeta('--rz-page-fg_f',         "pages",   "description of this var", "color", 'var(--rz-fg-focus)'),
createMeta('--rz-page-sz',           "pages",   "description of this var", "size", 'var(--rz-text-sz)'),
createMeta('--rz-page-head-pad',     "pages",   "Defines page header padding.", "size", '1rem'),
createMeta('--rz-page-head-bg',      "pages",   "Defines page header background color.", "color", '#484848'),
createMeta('--rz-page-head-fg',      "pages",   "Defines page header foreground.", "color", '#fff'),
createMeta('--rz-page-head-sz',      "pages",   "Defines page header text size.", "size", '2rem'),
createMeta('--rz-page-body-pad',     "pages",   "Defines page body padding", "color", '0 1rem'),
createMeta('--rz-page-foot-pad',     "pages",   "Defines page footer padding.", "size", '1rem'),
createMeta('--rz-page-foot-bg',      "pages",   "Defines page footer background color.", "color", '#414345'),
createMeta('--rz-page-foot-fg',      "pages",   "Defines page footer text color.", "color", '#e5b200'),
createMeta('--rz-page-foot-sz',      "pages",   "Defines page footer text size.", "size", '1rem'),
createMeta('--rz-side-bg',           "others",   "description of this var", "color", 'var(--rz-page-bg)'),
createMeta('--rz-pane-pad',          "panes and panels",   "Defines padding for an abstract pane.", "size", '0'),
createMeta('--rz-pane-bg',           "panes and panels",   "Defines background color for an abstract pane.", "color", 'var(--rz-bg-paper-0)'),
createMeta('--rz-pane-fg',           "panes and panels",   "Defines text color for an abstract pane.", "color", 'var(--rz-fg-text)'),
createMeta('--rz-pane-sz',           "panes and panels",   "Defines text size for an abstract pane.", "color", 'inherit'),
createMeta('--rz-pane-bc',           "panes and panels",   "Defines border color for an abstract pane.", "color", 'inherit'),
createMeta('--rz-pane-w-small',      "panes and panels",   "description of this var", "size", '30em'),
createMeta('--rz-pane-w-mid',        "panes and panels",   "description of this var", "size", '50em'),
createMeta('--rz-pane-head-pad',     "panes and panels",   "Defines padding for an abstract pane's head.", "size", '1em'),
createMeta('--rz-pane-head-bg',      "panes and panels",   "Defines background color for an abstract pane's head.", "color", 'var(--rz-pane-bg)'),
createMeta('--rz-pane-head-fg',      "panes and panels",   "Defines text color for an abstract pane's head.", "color", 'var(--rz-fg-title-1)'),
createMeta('--rz-pane-head-sz',      "panes and panels",   "Defines text size for an abstract pane's head.", "size", 'inherit'),
createMeta('--rz-pane-head-bc',      "panes and panels",   "Defines border color for an abstract pane's head.", "color", 'inherit'),
createMeta('--rz-pane-body-pad',     "panes and panels",   "Defines padding for an abstract pane's body.", "size", '1em'),
createMeta('--rz-pane-body-bg',      "panes and panels",   "Defines background color for an abstract pane's body.", "color", 'inherit'),
createMeta('--rz-pane-body-fg',      "panes and panels",   "Defines text color for an abstract pane's body.", "color", 'inherit'),
createMeta('--rz-pane-body-sz',      "panes and panels",   "Defines text size for an abstract pane's body.", "size", 'inherit'),
createMeta('--rz-pane-body-bc',      "panes and panels",   "Defines border color for an abstract pane's body.", "color", 'inherit'),
createMeta('--rz-pane-foot-pad',     "panes and panels",   "Defines padding for an abstract pane's footer.", "other", '1em'),
createMeta('--rz-pane-foot-bg',      "panes and panels",   "Defines background color for an abstract pane's footer.", "color", 'var(--rz-pane-bg)'),
createMeta('--rz-pane-foot-fg',      "panes and panels",   "Defines text color for an abstract pane's footer.", "color", 'var(--rz-pane-fg)'),
createMeta('--rz-pane-foot-sz',      "panes and panels",   "Defines text size for an abstract pane's footer.", "size", 'inherit'),
createMeta('--rz-pane-foot-bc',      "panes and panels",   "Defines border color for an abstract pane's footer.", "color", 'inherit'),
createMeta('--rz-card-pad',          "cards",  "Defines padding for an abstract card.", "other", '0'),
createMeta('--rz-card-bc',           "cards",  "Defines border color for an abstract card.", "color", 'var(--rz-gray-8)'),
createMeta('--rz-card-br',           "cards",  "description of this var", "size", '6px'),
createMeta('--rz-card-shadow',       "cards",  "Defines shadow dimensions and color for an abstract card.", "other", '0 0 16px 0 #00000014'),
createMeta('--rz-card-bg',           "cards",  "Defines background color for an abstract card.", "color", 'var(--rz-pane-bg)'),
createMeta('--rz-card-fg',           "cards",  "Defines text color for an abstract card.", "color", 'var(--rz-pane-fg)'),
createMeta('--rz-card-sz',           "cards",  "Defines text size for an abstract card.", "size", 'inherit'),
createMeta('--rz-card-head-pad',     "cards",  "Defines padding for an abstract card's head.", "other", '0.75rem 0.5rem'),
createMeta('--rz-card-head-bg',      "cards",  "Defines background color for an abstract card's head.", "color", 'var(--rz-card-fg)'),
createMeta('--rz-card-head-fg',      "cards",  "Defines text color for an abstract card's head.", "color", 'var(--rz-card-bg)'),
createMeta('--rz-card-head-sz',      "cards",  "Defines text size for an abstract card's head.", "size", 'inherit'),
createMeta('--rz-card-head-bc',      "cards",  "Defines border color for an abstract card's head.", "color", 'inherit'),
createMeta('--rz-card-body-pad',     "cards",  "Defines padding for an abstract card's body.", "other", '1em'),
createMeta('--rz-card-body-bg',      "cards",  "Defines background color for an abstract card's body.", "color", 'inherit'),
createMeta('--rz-card-body-fg',      "cards",  "Defines text color for an abstract card's body.", "color", 'inherit'),
createMeta('--rz-card-body-sz',      "cards",  "Defines text size for an abstract card's body.", "size", 'var(--rz-card-sz)'),
createMeta('--rz-card-body-bc',      "cards",  "Defines border color for an abstract card's body.", "color", 'inherit'),
createMeta('--rz-card-foot-pad',     "cards",  "Defines padding for an abstract card's footer.", "other", '0 1em'),
createMeta('--rz-card-foot-bg',      "cards",  "Defines background color for an abstract card's footer.", "color", 'var(--rz-card-fg)'),
createMeta('--rz-card-foot-fg',      "cards",  "Defines text color for an abstract card's footer.", "color", 'var(--rz-card-bg)'),
createMeta('--rz-card-foot-sz',      "cards",  "Defines text size for an abstract card's footer.", "size", 'inherit'),
createMeta('--rz-card-foot-bc',      "cards",  "Defines border color for an abstract card's footer.", "color", 'inherit'),
createMeta('--rz-dialog-pad',        "dialogs",   "Defines padding for an abstract dialog.", "other", '0'),
createMeta('--rz-dialog-bc',         "dialogs",   "Defines border color for an abstract card dialog.", "color", 'var(--rz-gray-8)'),
createMeta('--rz-dialog-br',         "dialogs",   "description of this var", "size", '6px'),
createMeta('--rz-dialog-shadow',     "dialogs",   "Defines shadow dimensions and color for an abstract dialog.", "other", '0 0 16px 0 #00000014'),
createMeta('--rz-dialog-bg',         "dialogs",   "Defines background color for an abstract dialog.", "color", 'var(--rz-pane-bg)'),
createMeta('--rz-dialog-fg',         "dialogs",   "Defines text color for an abstract dialog.", "color", 'var(--rz-pane-fg)'),
createMeta('--rz-dialog-sz',         "dialogs",   "Defines text size for an abstract dialog.", "size", 'inherit'),
createMeta('--rz-dialog-head-pad',   "dialogs",   "Defines padding for an abstract dialog's head.", "other", '0.75rem 0.5rem'),
createMeta('--rz-dialog-head-bg',    "dialogs",   "Defines backgorund color for an abstract dialog's head.", "color", 'var(--rz-dialog-fg)'),
createMeta('--rz-dialog-head-fg',    "dialogs",   "Defines text color for an abstract dialog's head.", "color", 'var(--rz-dialog-bg)'),
createMeta('--rz-dialog-head-sz',    "dialogs",   "Defines text size for an abstract dialog's head.", "size", 'inherit'),
createMeta('--rz-dialog-head-bc',    "dialogs",   "Defines border color for an abstract dialog's head.", "color", 'inherit'),
createMeta('--rz-dialog-body-pad',   "dialogs",   "Defines padding for an abstract dialog's body.", "other", '1em'),
createMeta('--rz-dialog-body-bg',    "dialogs",   "Defines background color for an abstract dialog's body.", "color", 'inherit'),
createMeta('--rz-dialog-body-fg',    "dialogs",   "Defines text color for an abstract dialog's body.", "color", 'inherit'),
createMeta('--rz-dialog-body-sz',    "dialogs",   "Defines text size for an abstract dialog's body.", "size", 'var(--rz-dialog-sz)'),
createMeta('--rz-dialog-body-bc',    "dialogs",   "Defines border color for an abstract dialog's body.", "color", 'inherit'),
createMeta('--rz-dialog-foot-pad',   "dialogs",   "Defines padding for an abstract dialog's footer.", "other", '0 1em'),
createMeta('--rz-dialog-foot-bg',    "dialogs",   "Defines background color for an abstract dialog's footer.", "color", 'var(--rz-dialog-fg)'),
createMeta('--rz-dialog-foot-fg',    "dialogs",   "Defines text color for an abstract dialog's footer.", "color", 'var(--rz-dialog-bg)'),
createMeta('--rz-dialog-foot-sz',    "dialogs",   "Defines text size for an abstract dialog's footer.", "size", 'inherit'),
createMeta('--rz-dialog-foot-bc',    "dialogs",   "Defines border color for an abstract dialog's footer.", "color", 'inherit'),
createMeta('--rz-popup-pad',         "popups",  "Defines the padding for an abstract popup.", "other", '0'),
createMeta('--rz-popup-bg',          "popups",  "Defines the background color for an abstract popup.", "color", 'var(--rz-card-bg)'),
createMeta('--rz-popup-fg',          "popups",  "Defines the foreground color for an abstract popup.", "color", 'var(--rz-card-fg)'),
createMeta('--rz-popup-bc',          "popups",  "Defines the border color for an abstract popup.", "color", 'var(--rz-gray-8)'),
createMeta('--rz-popup-br',          "popups",  "description of this var", "color", 'var(--rz-card-br)'),
createMeta('--rz-popup-sz',          "popups",  "Defines the text size for an abstract popup.", "size", 'unset'),
createMeta('--rz-popup-head-pad',    "popups",  "Defines the padding for an abstract popup header.", "other", '1em'),
createMeta('--rz-popup-head-bg',     "popups",  "Defines thebackground color for an abstract popup header.", "color", 'var(--rz-popup-fg)'),
createMeta('--rz-popup-head-fg',     "popups",  "Defines text color for an abstract popup header.", "color", 'var(--rz-popup-bg)'),
createMeta('--rz-popup-head-sz',     "popups",  "Defines text size for an abstract popup header.", "size", 'unset'),
createMeta('--rz-popup-body-pad',    "popups",  "Defines padding for an abstract popup body.", "other", '1em'),
createMeta('--rz-popup-body-bg',     "popups",  "Defines background color for an abstract popup body.", "color", 'unset'),
createMeta('--rz-popup-body-fg',     "popups",  "Defines text color for an abstract popup body.", "color", 'unset'),
createMeta('--rz-popup-body-sz',     "popups",  "Defines text size for an abstract popup body.", "size", 'var(--rz-popup-sz)'),
createMeta('--rz-popup-foot-pad',    "popups",  "Defines padding for an abstract popup footer.", "other", '1em'),
createMeta('--rz-popup-foot-bg',     "popups",  "Defines background color for an abstract popup footer.", "color", 'var(--rz-popup-fg)'),
createMeta('--rz-popup-foot-fg',     "popups",  "Defines text color for an abstract popup footer.", "color", 'var(--rz-popup-bg)'),
createMeta('--rz-popup-foot-sz',     "popups",  "Defines text size for an abstract popup footer.", "size", 'unset'),
createMeta('--rz-popup-shadow',      "popups",  "Defines shadow for an abstract popup.", "other", '8px 8px 5px var(--rz-fg-text)'),
createMeta('--rz-panel-pad',         "panes and panels",  "Defines padding for an abstract panel.", "other", '0'),
createMeta('--rz-panel-bg',          "panes and panels",  "Defines background color for an abstract panel.", "color", 'var(--rz-pane-bg)'),
createMeta('--rz-panel-fg',          "panes and panels",  "Defines text color for an abstract panel.", "color", 'var(--rz-pane-fg)'),
createMeta('--rz-panel-sz',          "panes and panels",  "Defines text size for an abstract panel.", "size", 'inherit'),
createMeta('--rz-panel-bc',          "panes and panels",  "Defines border color for an abstract panel.", "color", 'inherit'),
createMeta('--rz-panel-head-pad',    "panes and panels",  "Defines padding for an abstract panel header.", "other", '1em'),
createMeta('--rz-panel-head-bg',     "panes and panels",  "Defines background color for an abstract panel header.", "color", 'var(--rz-panel-fg)'),
createMeta('--rz-panel-head-fg',     "panes and panels",  "Defines text color for an abstract panel header.", "color", 'var(--rz-panel-bg)'),
createMeta('--rz-panel-head-sz',     "panes and panels",  "Defines text size for an abstract panel header.", "size", 'inherit'),
createMeta('--rz-panel-head-bc',     "panes and panels",  "Defines border color for an abstract panel header.", "color", 'inherit'),
createMeta('--rz-panel-body-pad',    "panes and panels",  "Defines padding for an abstract panel body.", "other", '1em'),
createMeta('--rz-panel-body-bg',     "panes and panels",  "Defines background color for an abstract panel body.", "color", 'uninheritset'),
createMeta('--rz-panel-body-fg',     "panes and panels",  "Defines text color for an abstract panel body.", "color", 'inherit'),
createMeta('--rz-panel-body-sz',     "panes and panels",  "Defines text size for an abstract panel body.", "size", 'var(--rz-panel-sz)'),
createMeta('--rz-panel-body-bc',     "panes and panels",  "Defines border color for an abstract panel body.", "color", 'inherit'),
createMeta('--rz-panel-foot-pad',    "panes and panels",  "Defines padding for an abstract panel footer.", "other", '1em'),
createMeta('--rz-panel-foot-bg',     "panes and panels",  "Defines background color for an abstract panel footer.", "color", 'var(--rz-panel-fg)'),
createMeta('--rz-panel-foot-fg',     "panes and panels",  "Defines text color for an abstract panel footer.", "color", 'var(--rz-panel-bg)'),
createMeta('--rz-panel-foot-sz',     "panes and panels",  "Defines text size for an abstract panel footer.", "size", 'inherit'),
createMeta('--rz-panel-foot-bc',     "panes and panels",  "Defines border color for an abstract panel footer.", "color", 'inherit'),
createMeta('--rz-block-pad',         "blocks boxes and cells",   "Defines padding for an abstract block.", "other", '0'),
createMeta('--rz-block-bg',          "blocks boxes and cells",   "Defines background color for an abstract block.", "color", 'inherit'),
createMeta('--rz-block-fg',          "blocks boxes and cells",   "Defines text color for an abstract block.", "color", 'inherit'),
createMeta('--rz-block-sz',          "blocks boxes and cells",   "Defines text size for an abstract block.", "size", 'inherit'),
createMeta('--rz-block-bc',          "blocks boxes and cells",   "Defines border color for an abstract block.", "color", 'none'),
createMeta('--rz-box-bg',            "blocks boxes and cells",   "Defines background color for an abstract box.", "color", 'inherit'),
createMeta('--rz-box-fg',            "blocks boxes and cells",   "Defines text color for an abstract box.", "color", 'inherit'),
createMeta('--rz-box-sz',            "blocks boxes and cells",   "Defines text size for an abstract box.", "size", 'inherit'),
createMeta('--rz-box-bc',            "blocks boxes and cells",   "Defines border color for an abstract box.", "color", 'var( --rz-gray-6 )'),
createMeta('--rz-box-bw',            "blocks boxes and cells",   "description of this var", "other", '2px'),
createMeta('--rz-box-bt',            "blocks boxes and cells",   "description of this var", "color", 'var( --rz-bt )'),
createMeta('--rz-box-border',        "blocks boxes and cells",   "Defines the border for an abstract box.", "color", 'var(--rz-box-bw) var(--rz-box-bt) var(--rz-box-bc)'),
createMeta('--rz-box-br',            "blocks boxes and cells",   "description of this var", "size", '0'),
createMeta('--rz-box-pad',           "blocks boxes and cells",   "Defines the padding for an abstract box.", "other", '0.75rem'),
createMeta('--rz-cell-pad',          "blocks boxes and cells",   "Defines the padding for an abstract cell.", "other", '0'),
createMeta('--rz-cell-bg',           "blocks boxes and cells",   "Defines the background color for an abstract cell.", "color", 'inherit'),
createMeta('--rz-cell-fg',           "blocks boxes and cells",   "Defines the text color for an abstract cell.", "color", 'inherit'),
createMeta('--rz-cell-sz',           "blocks boxes and cells",   "Defines the text size for an abstract cell.", "size", 'inherit'),
createMeta('--rz-cell-bc',           "blocks boxes and cells",   "Defines the border color for an abstract cell.", "color", 'inherit'),
createMeta('--rz-co-h',              "controls fields and forms",   "Defines header size for an RZ control.", "size", '25px'),
createMeta('--rz-co-bg',             "controls fields and forms",   "Defines background color for an RZ control.", "color", 'var(--rz-block-bg)'),
createMeta('--rz-co-fg',             "controls fields and forms",   "Defines text color for an RZ control.", "color", 'var(--rz-block-fg)'),
createMeta('--rz-co-fg-ph',          "controls fields and forms",   "description of this var", "color", 'var(--rz-block-fg)'),
createMeta('--rz-co-bc',             "controls fields and forms",   "Defines border color for an RZ control.", "color", 'var(--rz-gray-7)'),
createMeta('--rz-co-input-fg',       "controls fields and forms",   "Defines text color for an RZ control input.", "color", 'inherit'),
createMeta('--rz-co-input-bg',       "controls fields and forms",   "Defines background color for an RZ control input.", "color", 'inherit'),
createMeta('--rz-co-input-sz',       "controls fields and forms",   "Defines text size for an RZ control input.", "size",  '1em'),
createMeta('--rz-co-input-bc',       "controls fields and forms",   "Defines border color for an RZ control input.", "color", 'var(--rz-gray-7)'),
createMeta('--rz-co-input-pad',      "controls fields and forms",   "Defines padding for an RZ control input.", "other", '0.6em'),
createMeta('--rz-list-style',        "lists",   "Defines the style for any abstract list. The style of the list is how the items will be ordered, e.g. numbered, dased, etc.", "color", 'none'),
createMeta('--rz-list-item-pad',     "lists",   "Defines the padding for items in abstract list.", "other", '0.25rem 0.5rem'),
createMeta('--rz-list-item-bw',      "lists",   "description of this var", "other", '0'),
createMeta('--rz-list-item-bc',      "lists",   "Defines the border color for items in abstract list.", "color", 'var(--rz-gray-7)'),
createMeta('--rz-list-item-fg',      "lists",   "Defines the text color for items in abstract list.", "color", 'var(--rz-gray-3)'),
createMeta('--rz-list-item-bg',      "lists",   "Defines the background color for items in abstract list.", "color", 'white'),
createMeta('--rz-list-item-bg-1',    "lists",   "description of this var", "color", 'var(--rz-list-item-bg)'),
createMeta('--rz-list-item-bg-2',    "lists",   "description of this var", "color", '#f0f0f0'),
createMeta('--rz-list-item-bg_h',    "lists",   "description of this var", "color", 'cornsilk'),
createMeta('--rz-field-label-sz',    "controls fields and forms",  "Defines the text size for an abstract label in a field.", "size",  '0.8em'),
createMeta('--rz-field-label-fg',    "controls fields and forms",  "Defines the text color for an abstract label in a field.", "color", 'var(--rz-fg-dimmed)'),
createMeta('--rz-field-ph-fg',       "controls fields and forms",  "description of this var", "color", 'var(--rz-fg-faint)'),
createMeta('--rz-field-ph-fg_f',     "controls fields and forms",  "description of this var", "color", 'var(--rz-fg-dimmed)'),
createMeta('--rz-field-ph-sz',       "controls fields and forms",  "description of this var", "size",  '0.9em'),
createMeta('--rz-field-bw',          "controls fields and forms",  "description of this var", "other", '1px'),
createMeta('--rz-form-pad',          "controls fields and forms",  "Defines the padding for an abstract form.", "other", '1rem'),
createMeta('--rz-form-group-bc',     "controls fields and forms",  "description of this var", "color", 'var( --rz-box-bc, gray )'),
createMeta('--rz-form-group-border', "controls fields and forms",  "description of this var", "other", 'var( --rz-box-bw ) var(--rz-box-bt) var(--rz-form-group-bc)'),
]
